services:
  db:
    image: postgres:17.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: dzencode
      POSTGRES_USER: dzencode
      POSTGRES_PASSWORD: dzencode
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  broker:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
volumes:
  postgres-data:
    driver: local
