# Generated by Django 5.2 on 2025-05-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
