# Generated by Django 5.2 on 2025-05-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_crated',
            new_name='datetime_created',
        ),
    ]
