# Generated by Django 5.2 on 2025-05-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comment_user_comment_email_comment_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
