# Generated by Django 5.2 on 2025-04-30 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['gif', 'jpg', 'png', 'txt'])])),
                ('datetime_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
