# Generated by Django 5.2 on 2025-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('filetype', models.CharField(max_length=12)),
                ('is_image', models.BooleanField()),
                ('datetime_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
