# Generated by Django 5.2 on 2025-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filetype',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
