# Generated by Django 5.2 on 2025-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_attachment_file_alter_attachment_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_image',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
