# Generated by Django 5.2 on 2025-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_attachment_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='resized',
            field=models.BooleanField(default=False),
        ),
    ]
