# Generated by Django 5.2 on 2025-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_attachment_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='resized',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
